services:
  db:
    env_file:
      - .db.env
    image: postgres:latest
    container_name: savannafaces_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - savannafaces_network

  cache:
    image: redis:latest
    container_name: savannafaces_cache
    ports:
      - "6380:6379"
    networks:
      - savannafaces_network

  web:
    build: .
    container_name: savannafaces_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    networks:
      - savannafaces_network

networks:
  savannafaces_network:
    driver: bridge

volumes:
  pgdata: